### ISSUE TITLE
Need help implement Nuclei for async-tungstenite (docs pretty sparse in some places)

### ISSUE THREAD

**Issue by d4h0** [vertexclique/nuclei#16]
Hi,

I'd like to add support for Nuclei to [async-tungstenite](https://docs.rs/async-tungstenite/0.8.0/async_tungstenite/index.html) (a crate for WebSocket clients and server), but I'm relatively new to Rust and the docs of Nuclei seem to be pretty sparse in some places.

It would be great if someone would answer a few questions I have :)

My plan, for my own crate (which will use async-tungstenite), is to optionally accept an AgnostikExecutor trait object. If no executor is passed, I will create one.

(Btw., It would be great if there was a way to access the global executer ("const EXECUTER") or a generic function that generates an executer according to the selected feature flags. Something like `Agnostic::create_executer()` instead of using feature flags with the executer-specific functions (as `Agnostic` does internally). It's kind of funny that there isn't an agnostic way to create an `AgnostikExecutor` :)).

My first problem is, that I don't know how to use Nuclei with my optionally passed in or by myself created executer. It seems Nuclei uses the globally created executer internally.

I didn't see any information regarding this in the docs, and none of the examples creates its own executer.

My second problem is that [`drive`](https://docs.rs/nuclei/0.1.1/nuclei/fn.drive.html) is basically undocumented and I don't know when, where, and how to use it.

Without Nuclei, I have a `runtime.block_on` that executes my async code.

Do I need to replace that with a call of `drive`, or do I need to start a separate `drive` future or thread? (As seen in [this example](https://github.com/vertexclique/nuclei/blob/master/examples/h1-server.rs))

The Bastion project looks very interesting to me, and I'm glad I found a reason to try some of its parts out :)

**Comment by vertexclique** [comment]
> (Btw., It would be great if there was a way to access the global executer ("const EXECUTER") or a generic function that generates an executer according to the selected feature flags. Something like Agnostic::create_executer() instead of using feature flags with the executer-specific functions (as Agnostic does internally). It's kind of funny that there isn't an agnostic way to create an AgnostikExecutor :)).

Thanks for the suggestion, since dependencies are different for every executor, that was the initial way we've come up with. We can refine it further down with macros.

> My first problem is, that I don't know how to use Nuclei with my optionally passed in or by myself created executer. It seems Nuclei uses the globally created executer internally.

True, for using yours, if open-source, you can add to agnostik, if not, you can implement AgnostikExecutor trait. That said, there we need to have a mechanism for custom executors too. probably using trait bounds to use the executor.

> My second problem is that drive is basically undocumented and I don't know when, where, and how to use it.

Drive is taking a future and polling it, you can write your own code inside that future and you don't call block_on on it. 
Or as a separate future, it can work parallel to some other async code like the link that you've made to the examples.

> Do I need to replace that with a call of drive, or do I need to start a separate drive future or thread? (As seen in this example)

Both of them are ok, should work by default.

> The Bastion project looks very interesting to me, and I'm glad I found a reason to try some of its parts out :)

That's nice to hear! We are looking forward for feedback and improvements like these.

**Comment by d4h0** [comment]
> Thanks for the suggestion, since dependencies are different for every executor, that was the initial way we've come up with. We can refine it further down with macros.

Would the following be a good approach? 

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9757340cb09742c2adde4ad337149deb)

If so, I probably could send a PR that implements this feature.

If I should send a PR:

- Would you prefer a different name?  (Maybe 'get_executor' or 'create_executor'?)
- Should the function panic or return a `Result`?
- Would it make sense to create a function 'executers' that returns a `Vec` of all activated executors? (In case more than one executor is activated. However, I'm not even sure if that makes sense to do. If not, we probably always should panic if several executors are activated)

>> My first problem is, that I don't know how to use Nuclei with my optionally passed in or by myself created executer. It seems Nuclei uses the globally created executer internally.

> True, for using yours, if open-source, you can add to agnostik, if not, you can implement AgnostikExecutor trait. That said, there we need to have a mechanism for custom executors too. probably using trait bounds to use the executor.

It seems what I wrote wasn't clear. I didn't mean *'creating a completely new executer'*, I meant *'creating an instance of an `AgnostikExecutor` executor'*.

So the code of a user of my crate could look like this:

```
use my_crate::my_fn;
use std::sync::Arc;

my_fn(Arc::new(Some(nuclei::Agnostic::bastion())));
```

If the user passes in `None`, I will create the executor myself (for example with my `executor` function from above), otherwise, I will use the executer the user has supplied.

My question is if there is a way to use this executor somehow instead of the executor that Agnostic creates globally?

Or does `drive` automatically use the executor that my user or I have created? I'm also new to async Rust, so maybe I'm missing something fundamental.

**Comment by d4h0** [comment]
After thinking about it a little more, I think the `executor` function should just return the global executor.

But it seems like it would be better to replace [the following code](https://docs.rs/agnostik/0.1.4/src/agnostik/lib.rs.html#142):

```rust
#[cfg(feature = "runtime_bastion")]
static EXECUTOR: Lazy<executors::BastionExecutor> = Lazy::new(|| executors::BastionExecutor);

#[cfg(feature = "runtime_asyncstd")]
static EXECUTOR: Lazy<executors::AsyncStdExecutor> = Lazy::new(|| executors::AsyncStdExecutor);

#[cfg(feature = "runtime_tokio")]
static EXECUTOR: Lazy<executors::TokioExecutor> = Lazy::new(|| executors::TokioExecutor::new());

#[cfg(feature = "runtime_smol")]
static EXECUTOR: Lazy<executors::SmolExecutor> = Lazy::new(|| executors::SmolExecutor);
```

with something like my implementation. In case a user activates no or several executor flags. 

Something like:

```rust
static EXECUTOR: Lazy<dyn AgnostikExecutor> = Lazy::new(|| /* code from the original 'executor' function above */);

pub fn executor() -> impl AgnostikExecutor {
    EXECUTOR
}
```

(Not sure if the code would work like that).

I think returning the global executor would make the crate more flexible to use.

Then crate creators can accept an optional `AgnostikExecutor` and get the global one if none is supplied. End users just need to select an executor via a feature flag and can use the global Agnostic functions (`spawn`, etc.) to run their code.

**Comment by vertexclique** [comment]
We are not using agnostik anymore. Supported runtimes are listed in the documentation.
