### ISSUE TITLE
nuclei.bastion.rs isded

### ISSUE THREAD

**Issue by qm3ster** [vertexclique/nuclei#23]
is linked
but is ded

**Comment by o0Ignition0o** [comment]
Thanks for submitting the issue!

I didn't know nuclei.bastion.rs was a thing, @vertexclique thoughts? should we do something ?

**Comment by qm3ster** [comment]
It's linked in the About of this repo's GitHub metadata.

**Comment by o0Ignition0o** [comment]
I wonder if there used to be an actual page behind this and we should fix it

**Comment by vertexclique** [comment]
There wasn't an actual webpage. I put it there as a placeholder back in time. I don't have time to prep a webpage atm. Sorry.

**Comment by qm3ster** [comment]
Just reminding you that it's still there, in case you didn't mean to leave it.
If you did, say nothing and it will be known :v
