### ISSUE TITLE
[io_uring] Configuration option kernel_poll_only might be enabling user-mode CQ polling

### ISSUE THREAD

**Issue by LtdJorge** [vertexclique/nuclei#40]
If I've understood nuclei's and io_uring's documentation correctly, I believe the last commit to master enables both kernel polling for SQ and application polling for CQ while selecting `kernel_poll_only`, see this line:
https://github.com/vertexclique/nuclei/commit/323b1d04d8a03f17bfaeb341599a6db6a84c10a9#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdR116

`kernel_poll_only` should enable `sqpoll` and disable aggressive polling. Both `kernel_poll_only` and `low_latency_driven` set the values to the same options.

**Comment by vertexclique** [comment]
Do you want to open a PR for that? 😃 I forgot to fix that part. Left locally, but I would like to have people engaging :) It is ok, if you don't want to, I will fix that.

**Comment by LtdJorge** [comment]
Sure, done. I fumbled it a bit by typing fals instead of false, since I forked from the Github webpage as I didn’t want to clone locally for such a simpke change. Oh well…
